// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-wN9-ZZppsK0dlxJmb3zVGvdlBUgrko',
    appId: '1:393783388275:web:4bfe9f64b5eb5a2e772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    authDomain: 'chat-68e71.firebaseapp.com',
    storageBucket: 'chat-68e71.firebasestorage.app',
    measurementId: 'G-76QR2RGXKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuTteQhicJMc6cGSYdnwcGzvrxccYhsI',
    appId: '1:393783388275:android:7b6fa0adb94f290b772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9idUkwMjkoHR7Mgx1Xftc7cAnHx5i0Sc',
    appId: '1:393783388275:ios:e0d2b97dd180a877772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
    iosBundleId: 'com.example.registerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9idUkwMjkoHR7Mgx1Xftc7cAnHx5i0Sc',
    appId: '1:393783388275:ios:e0d2b97dd180a877772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
    iosBundleId: 'com.example.registerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-wN9-ZZppsK0dlxJmb3zVGvdlBUgrko',
    appId: '1:393783388275:web:3524d2cee0f0d977772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    authDomain: 'chat-68e71.firebaseapp.com',
    storageBucket: 'chat-68e71.firebasestorage.app',
    measurementId: 'G-KMXP86V4LN',
  );

}